version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=aidhaiosudhaishudiuads
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_LOGGER=true
      - DISCORD_URL=https://discord.com/api/webhooks/1164774618339475506/6N1h5tZrHOfGCnqnBN9zhMVGmxSU0YdCXKTV2d1hPuiaY-G7or_Ghz9kberchyasXpN6
      - DISCORD_USERNAME=Zipline
      - DISCORD_UPLOAD_USERNAME="Zipline Uploads"
      - DISCORD_SHORTEN_USERNAME="Zipline URLs"
      - DISCORD_AVATAR_URL=https://cdn.aidenpearce.space/favicon.ico
      - OAUTH_DISCORD_CLIENT_ID=514153552789372929
      - OAUTH_DISCORD_CLIENT_SECRET=jzTQJDsJbTw7qxR3WEPgFpUik_YAjL9v
      - FEATURES_OAUTH_REGISTRATION=false
      - RATELIMIT_USER=5
      - RATELIMIT_ADMIN=1
      - WEBSITE_TITLE=Aiden's Zipline
      - WEBSITE_SHOW_FILES_PER_USER=true
      - WEBSITE_SHOW_VERSION=true
    volumes:
      - './uploads:/zipline/uploads'
      - './public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data:
